#!/usr/bin/expect

log_file /usercode/logfile2.txt

spawn ../file

expect "msh> "
send "ls  > temp.txt\n"
expect "msh> "
send "diff temp.txt /usercode/temp.sol\n"
expect "msh> "
send "sort -r < temp.txt\n"
expect "msh> "
send "cd home\n"
expect "msh> "
send "pwd\n"
expect "msh> "
send "cd ..\n"
expect "msh> "
send "pwd\n"
expect "msh> "
send "sort < temp.txt > sorted-temp.txt\n"
expect "msh> "
send "sort < new.txt\n"
expect "msh> "
send "exit\n"
