const ADD_EDITORID = 'ADD_EDITASSIGNMENT_EDITORID';
const ADD_PARTID = 'ADD_EDITASSIGNMENT_PARTID';
const REMOVE_EDITORID = 'REMOVE_EDITASSIGNMENT_EDITORID';
const REMOVE_PARTID = 'REMOVE_EDITASSIGNMENT_PARTID';
const SET_EDITOR = 'SET_EDITASSIGNMENT_EDITOR';
const SET_PART = 'SET_EDITASSIGNMENT_PART';
const UNSET_EDITOR = 'UNSET_EDITASSIGNMENT_EDITOR';
const UNSET_PART = 'UNSET_EDITASSIGNMENT_PART';

export {
  ADD_EDITORID,
  ADD_PARTID,
  REMOVE_EDITORID,
  REMOVE_PARTID,
  SET_EDITOR,
  SET_PART,
  UNSET_EDITOR,
  UNSET_PART,
};
