const ADD_PARTID = 'ADD_EDITASSIGNMENT_PARTID';
const REMOVE_PARTID = 'REMOVE_EDITASSIGNMENT_PARTID';
const SET_PART = 'SET_EDITASSIGNMENT_PART';
const UNSET_PART = 'UNSET_EDITASSIGNMENT_PART';

export {
  ADD_PARTID,
  REMOVE_PARTID,
  SET_PART,
  UNSET_PART,
};
